version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  backend:
    image: backend:latest
    env_file:
      - ./Backend/.env
    environment: 
      DATABASE_HOST: mysql
    ports:
      - 3000:3000
    expose: 
      - 3000
    depends_on:
      mysql:
        condition: service_healthy
  frontend:
    image: frontend:latest
    environment:
      PORT: 8080
    ports:
      - 8080:8080